### ISSUE TITLE
Decryption methodology on JP 3.1.42

### ISSUE THREAD

**Issue by n0k0m3** [nobbyfix/AzurLaneSource#2]
How did you decrypt the new AssetsBundle on JP 3.1.42? And how did you find the decrypt function? You don't really have to answer to these questions but is the method of finding the new encryption/packing scheme requires il2cpp dumping?

Before this I used perfare's guide to decrypt AB and lua, but after JP update I can't anymore.

**Comment by nobbyfix** [comment]
I don't have the decryption function, i dumped the memory during the startup of the app and copied the decrypted scripts file from there.

**Comment by n0k0m3** [comment]
Thanks
